spring:
  datasource:
    url: jdbc:mysql://localhost:3306/climblog
    username: climblog_prod
    password: letmein
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
 #use this to easily get the database schema to build the database
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: climblog_db_create.sql